# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b30a55ae926e116b61f444d9a3b682fef09c61a028c02a47e6412aaa7000b056ee0a493b962708385a2364873466bc7492cd4c47c1af510abe29bb44a76df639

test:
  secret_key_base: dfd6aad2b372c05880a96570df6c3c3022be4c7d1691f7218295f0deca2226f87e2e942680ffa423bb2ae59412a29450fd49101c2e49488be9543ed2fbc88112

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
